name: c861f
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.3
  - python=3.11.14
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - asttokens==3.0.1
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - comm==0.2.3
      - debugpy==1.8.17
      - decorator==5.2.1
      - emoji==2.15.0
      - executing==2.2.1
      - filelock==3.19.1
      - fsspec==2025.9.0
      - idna==3.11
      - ipykernel==7.1.0
      - ipython==9.7.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.8
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyterlab-widgets==3.0.16
      - markupsafe==2.1.5
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - networkx==3.5
      - nltk==3.9.2
      - numpy==2.3.3
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pillow==11.3.0
      - platformdirs==4.5.0
      - prompt-toolkit==3.0.52
      - psutil==7.1.3
      - pure-eval==0.2.3
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyzmq==27.1.0
      - regex==2025.11.3
      - requests==2.32.5
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.9.1+cu126
      - torchtext==0.18.0
      - torchvision==0.24.1+cu126
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - widgetsnbextension==4.0.15
prefix: C:\Users\Sharjeel Mustafa\.conda\envs\c861f
