name: c861f
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.3
  - python=3.11.14
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - click==8.3.1
      - colorama==0.4.6
      - filelock==3.19.1
      - fsspec==2025.9.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.5
      - nltk==3.9.2
      - numpy==2.3.3
      - pillow==11.3.0
      - regex==2025.11.3
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.9.1+cu126
      - torchvision==0.24.1+cu126
      - tqdm==4.67.1
      - typing-extensions==4.15.0
prefix: C:\Users\Sharjeel Mustafa\.conda\envs\c861f
